### PR TITLE
Add preferred OSG license (ASL 2.0)

### PR DESCRIPTION
**Pull request by bbockelm**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Please fill out copyright year and owner:
Copyright 2017 University of Wisconsin-Madison

**Comment by bbockelm** [comment]
I don't think that's how it works; that section is just the boilerplate one should include if copy/pasting it into a source file.

I figured that Apache foundation projects would be good to mimic here:

https://github.com/apache/kafka/blob/trunk/LICENSE

**Comment by matyasselmeci** [comment]
I was going to say something to the effect of how about looking at a _real_ Apache foundation project, but apparently even httpd leaves that bit blank. So OK, go ahead.

**Comment by bbockelm** [comment]
Ahem.  Press the "approve" button then :)

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
