### PR TITLE
Added openssh-server to docker-osg-wn container (SOFTWARE-5314)

### PR DESCRIPTION
**Pull request by AidenCohen31**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hey @AidenCohen31 could you rebase [1][2] this to reword the commit based on recommendations for writing descriptive commit messages [3]? In particular, the commit should reference the Jira ticket that kicked off this work, e.g. `<your descriptive commit message> (SOFTWARE-5314)`

[1] https://www.atlassian.com/git/tutorials/merging-vs-rebasing
[2] https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase
[3] https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

EDIT: Also if you could edit the PR title to match the commit message, that'd be great (PR titles show up in the merge commit)

**Comment by AidenCohen31** [comment]
Changed commit message

**Comment by brianhlin** [comment]
Hi @AidenCohen31 , I think you may have caught the HEAD of `master` in your rebasing efforts and this has resulted in rewriting history for commits that have already been pushed to the main fork, which is a no-no. Note the different commit hash in the main fork (https://github.com/opensciencegrid/docker-osg-wn/commit/0d108cf837af456611763a4a6f22e4c1c31f3722) vs the one on your fork (https://github.com/opensciencegrid/docker-osg-wn/pull/15/commits/7f4090fe11f89ac9ace4b720663f639e42f48970) for the same change.

You can fix this with a bit of surgery:

1. On your branch, create a backup copy of the branch: `git checkout -b SOFTWARE-5314.backup patch-1`. 
2. Verify that your changes have been made on this new branch with `git log`
3. Change back to the branch corresponding to this PR: `git checkout patch-1`
4. Reset your branch based on `master`: `git reset --hard master`
5. Cherry pick your commit with the changes you want from the backup copy of your branch: `git cherry-pick SOFTWARE-5314.backup`
6. Verify that your changes have been made and that the hash of the previous commit matches the HEAD of `master` with `git log`
7. Force push to your GitHub fork

**Comment by AidenCohen31** [comment]
I think I correctly revised the history.

**Review by brianhlin — APPROVED** [review]
LGTM, thanks!

**Comment by brianhlin** [comment]
@mmascher once the builds complete in a few minutes, the latest containers should have sshd available!

**Pull request merged**
